# Generated by Django 4.2.1 on 2023-07-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_order_product_order_order_id_order_order_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='addrress1',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='addrress2',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
