# Generated by Django 4.2.3 on 2023-07-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_order_order_id_remove_order_sub_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='addrress1',
        ),
        migrations.RemoveField(
            model_name='order',
            name='addrress2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='email',
        ),
        migrations.RemoveField(
            model_name='order',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
