# Generated by Django 4.2.1 on 2023-06-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0003_tutor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutor',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
