# Generated by Django 4.2.1 on 2023-06-26 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0004_alter_tutor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='skills',
            field=models.TextField(default=''),
        ),
    ]
