# Generated by Django 4.2.1 on 2023-07-06 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0006_tutor_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tutor',
            name='user',
        ),
        migrations.AddField(
            model_name='tutor',
            name='full_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tutor',
            name='mobile_no',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='skills',
            field=models.CharField(max_length=100),
        ),
    ]
