# Generated by Django 4.2.1 on 2023-07-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0007_remove_tutor_name_remove_tutor_user_tutor_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
